priceConfig:
  growthFactor: 1.25 #Prices for upgrades are calculated as Price(upNum)=growthIncrement*growthFactor^upNum
  incrementFactor: 1.5 #growthIncrement is calculated as grInc(shopNum)=incrementConstant*incrementFactor^shopNum
  incrementConstant: 36.5

  shop: #Shop prices is calculated as constant*factor^shopNum - Where shopNum is on top of default num
    priceFactor: 2.5
    priceConstant: 5000

  prestige: #Prestige contents are calculated as constant*factor^rebirthNum
    multiplierFactor: 1.5
    multiplierConstant: 1
    requirementFactor: 1.65
    requirementConstant: 5110
  
scrollConfig:
  scrollSpeed: 1
  scrollIndicator: true
  scrollindicatorPadding: 20

popupConfig: #Config for the money popups in game
  size: 24
  angleVariance: 10

  positive: #When gaining money
    color: '#00b705'
    stroke: "#006908"
    prefix: '+'

  negative: #When spending money
    color: '#ff2e2e'
    stroke: "#690000"
    prefix: '-'

  neutral: #When no money is transfered. Fx if you dont have enough
    color: '#acacac'
    stroke: "#000000"
    prefix: ''

shopConfig:
  size: 70
  maxUpgrades: 20
  texture:
    grey: 'nettoSpriteGrey'
    progress: 'nettoSprite'
    managerGrey: 'managerGrey'
    managerProgress: 'managerProgress'
  menuButtons:
    upgradeButtonScale: 0.5
    upgrade1:
      icon: 'customerIcon'
      defaultValue: 4
      valueIncrement: 2
      valueSuffix: ''
    upgrade2:
      icon: 'cashierIcon'
      defaultValue: 100
      valueIncrement: 10
      valueSuffix: "%"
    upgrade3:
      icon: 'coinHandIcon'
      defaultValue: 3
      valueIncrement: 3
      valueSuffix: ''
    managerUpgrade1:
      icon: 'speedIcon'
      defaultValue: 100
      valueIncrement: 5
      valueSuffix: '%'
    managerUpgrade2:
      icon: 'multiplierIcon'
      defaultValue: 1
      valueIncrement: 0.05
      valueSuffix: 'x'


shops:
  - name: "Butik 1 (København)"
    x: 1000
    y: 700

  - name: "Butik 2 (Odense)"
    x: 600
    y: 800

  - name: "Butik 3 (Aarhus)"
    x: 550
    y: 550

  - name: "Butik 4 (Skagen)"
    x: 550
    y: 100

  - name: "Butik 5 (din mor)"
    x: 300
    y: 900

  - name: "Butik 6 (din far)"
    x: 600
    y: 700

  - name: "Butik 7 (Skåne)"
    x: 1200
    y: 100



menu:
  contentPadding: 0 #Padding between objects in menu.
  initialOffset: 280 #The offset of contents from top of menu

  upgradeMenu:
    name: 'Butikker'
    icon: 'shopIcon' #Matching an asset name
    index: 1 #Determines which slot it should be in.
    labelPadding: 60 #Padding between label and buttons
    labelSize: 35
    labelColor: '#ffffff' #Hex Value
    labelFontWeight: 'Medium' #Bold, SemiBold, Medium or Regular
  

  managerMenu:
    name: 'Managers'
    icon: 'managerIcon'
    index: 0
    labelPadding: 60 #Padding between label and buttons
    labelSize: 35
    labelColor: '#ffffff' #Hex Value
    labelFontWeight: 'Medium' #Bold, SemiBold, Medium or Regular



texture:
  shopButton:
    button: 'button'
    greyButton: 'greyButton'


  
  addButton:
    button: 'addButton'
    greyButton: 'addButtonGrey'
  prestigeMenuButton:
    button: 'prestigeMenuButton'
    greyButton: 'prestigeMenuButton'
  prestigeButton:
    button: 'prestigeButton'
    greyButton: 'prestigeButtonGrey'

sounds:
  - name: "clickSound"
    path: "assets/Sounds/click.mp3"
  - name: "collectSound"
    path: "assets/Sounds/collect2.mp3"
  - name: "denySound"
    path: "assets/Sounds/deny.mp3"
  - name: "purchaseSound"
    path: "assets/Sounds/collect.mp3"
  - name: "swoosh"
    path: "assets/Sounds/swipe.mp3"

#Fonts are looped in the GameScene and loaded from there.
fonts:
  - name: "KodeMonoRegular"    
    path: "assets/Fonts/KodeMono-Regular.ttf"
  - name: "KodeMonoMedium"    
    path: "assets/Fonts/KodeMono-Medium.ttf"
  - name: "KodeMonoSemiBold"    
    path: "assets/Fonts/KodeMono-SemiBold.ttf"
  - name: "KodeMonoBold"    
    path: "assets/Fonts/KodeMono-Bold.ttf"
  
#Assets are looped in the GameScene and loaded from there.
assets:
  #Prestige Assets
  - name: "prestigeMenuButton"
    path: "assets/PrestigeMenu/prestigeMenuButton.png"
  - name: "prestigeIcon"
    path: "assets/PrestigeMenu/prestigeIcon.png"
  - name: "prestigeMenuBackground"
    path: "assets/PrestigeMenu/prestigeMenuBackground.png"
  - name: "prestigeButton"
    path: "assets/PrestigeMenu/prestigeButton.png"
  - name: "prestigeButtonGrey"
    path: "assets/PrestigeMenu/prestigeButtonGrey.png"
  - name: "prestigeProgress"
    path: "assets/PrestigeMenu/prestigeProgress.png"
  - name: "prestigeProgressGrey"
    path: "assets/PrestigeMenu/prestigeProgressGrey.png"
  - name: "prestigeArrow"
    path: "assets/PrestigeMenu/prestigeArrow.png"
  - name: "fadedBackground"
    path: "assets/PrestigeMenu/fadedBackground.png"

  #Shop Assets
  - name: "managerProgress"
    path: "assets/Shops/managerProgress.png"
  - name: "managerGrey"
    path: "assets/Shops/managerGrey.png"
  - name: "nettoSprite"
    path: "assets/Shops/nettoSprite.png"
  - name: "nettoSpriteGrey"
    path: "assets/Shops/nettoSpriteGray.png"

  # General Assets
  - name: "map"
    path: "assets/DK-Kort.png"

  #UI Assets
  - name: "coin"
    path: "assets/UI/coin.png"
  - name: "moneyBackground"
    path: "assets/UI/moneyBackground.png"

  #Menu Assets
  # General Menu Assets
  - name: "menuBackground"
    path: "assets/Menu/menuBackground.png"
  - name: "inactiveMenuTab"
    path: "assets/Menu/inactiveMenuTab.png"
  - name: "activeMenuTab"
    path: "assets/Menu/activeMenuTab.png"
  - name: "scrollIndicator"
    path: "assets/Menu/scrollIndicator.png"

  - name: "shopIcon"
    path: "assets/Menu/shopIcon.png"
  - name: "managerIcon"
    path: "assets/Menu/managerIcon.png"

  - name: "button"
    path: "assets/Menu/button.png"
  - name: "greyButton"
    path: "assets/Menu/greyButton.png"
  - name: "addButton"
    path: "assets/Menu/addButton.png"
  - name: "addButtonGrey"
    path: "assets/Menu/addButtonGrey.png"
  
  - name: "customerIcon"
    path: "assets/Menu/customerIcon.png"
  - name: "cashierIcon"
    path: "assets/Menu/cashierIcon.png"
  - name: "coinHandIcon"
    path: "assets/Menu/coinHandIcon.png"
  - name: "speedIcon"
    path: "assets/Menu/speedIcon.png"
  - name: "multiplierIcon"
    path: "assets/Menu/multiplierIcon.png"
